clc;
clear all;
%序列重构
%8 8 8 6 6 6 6   最后一组拆开放后三组的末尾
% data = 'AATGTACAATGTGTAAAGCCGATCACACTCTGCCACTAAGTTAATGTGTGTGTGTGTGAGACGCAATGCCGCTAAGTACCTATTCGATGCGTCTGCGAAAATGTATATGTCTGCACCCTCTTGCCACGTTGTCGTTGTCGCTGCGCGTGCAAGGTCTGCCGCTGCCGATTACCACTATCCGGAACGCGCTAACGGATCACCCAGTCCCTTATGGTTATTCAACCGTTAGTATGAGTATCCAAGCCGATCCACATAGTACGAACTCTGTATGTCTGTGTAATCAATGTCAGGGTCTGCGAACAATAAGCGACCAGGCAACGAATTCGCTGCGCGTATGTCTGAGAAAATGTAAAGCCTTGCATCGGCATGCTCACCGGTGTAATTCCTATGCGGATACACATTGCCTAGTAACGACAGAAGCCGATCACACAGACGCTCTAGGCATAGCTTAACGAACAATTGTGCCGGAAGCGTATTGTTAATGTCTGCCGACAGTAAGTAAAGCCGATCACAGAACGCTAAGTTAATCTCACGTGTCGACCGATTCTAACTCGCTGCAGCCTCACACAATCCGGTGGTTTGTGCCACTAACATGCCAGGCGTTGGCGGTCCACCCTCACACACATTCAATAGCCTATTCAATAGCCTACGGTACTCATGCAATAAGCCTTCAGAGCCTCCCCTAATCGACACATGCGATGCGAAACCACCGGATAAGAGTCCCAACTCTGTCGGTTGCCTACGCTTTCCGGATGACAGTAACAAACGTTAGCTGAATACGCTAGGCCAATGCTGACGTGTGTTGTCTTCACCGAACCTAATCGAACACAAAGACTTTGCGTCTGCACGGTGAGGCCTGAATTGTTGGGTGTAAAGCTAAATCAATACAAGGTATGAGTACATATCGTGTGTGAGTCCATGCTTGCCTTAGCGTATGTCTGACTTAACGCTTAACTCAATGCGATGCGGTTCAACGTCTGTGGTAGACTGTCCCAACAAATCACGGCACAGATGTACCATATCGTGTGTGAGTCCCAACAAATCACGGCACAGATGTACCCTAATCGACACTGGCAAATCACAGAACATATCGTGTGTGAGAGGCATTTAGGCTCCAAGCCGATCCACACAGTACAATTGTGCCATGTTATGCTCATGCTAAAGTAAGAACCGTGCGTCTGTCACTTCGCATAGCAGTGCATCGGCATGCTCAAGCGTGTGTGTGAGTCCATTCGCAAGCGACCTACCGCGTGCGTTACCATTCATGAAACCGGTTGCACGGTTATGCTCTATCATGTATCCAACGTACCAAACACTGGTGGCAATGTAACGTTGCGATGCCTCATGCCGATTGAACCGTTGCCGATGTGAGTACAAACCGCGTATGAAATTGGCACGCAATATGCGTATGCGTAAGCCATTCATAAGCAATATGTAAACACTGTACTCATGCTCATTCAATTGTGCCTCACCGCGTGTGAACAATAACGGACGTAAGCCTACCAACGATTACTATAAGAAAAGCCGATCACAGCACAGATGTACCAATAGGTATGTCGTGTGTGTGAAACACAATAGTTGCGTATCCAGAACCAACGAAAGTTACCGTGCGAATAGGTGTGCCGTATTCCGTGTGCGACGCAGTGCCAACAAAAGTAACGTGTCATGTAGCGCTGCCTACCTACACAGTGACGATAGTGCCCGTGCGTTACCCATGGTTCCAAGGTCTGCCAATGGCAGACCGCTGTGTAGCCTAGCAAGCACACTGAACTAACTCAGTGGCCTTGAGGCTACGAAAAGTATCAATGCCCTGTCTGCGGCATTCAAACGCGTTGTGTTAAGTCCGTGATAGTACTAAAGCACACTCTCTGCAACGGATGGGCCTCCGCCTTGCAGTGCCGTGTGAGTCGTTGAGTATGAGGAACCAAGGAACTAACTCTTATCAATGTATTCCATATAGCCTGTGTGTGTGTGTCACATACCCTATAGGAACGATTACGTAGAGTGTGTGTGTGTGAGACCAGTCGGATGCATAGGGTACCAAAGCAAACCGAATATGTAAAGCTCAAGCGGTATCACTATCGCTGAGTATCCAAGGTCTGCCGTGTGAGTCGTTGAGTATGAGGAACCAAGGAATTACGGACCCATATCGTGAGGCAACAAAGAGCGACCATTGCCTGTGTGATCCAGAGGGTACCGTGCACGGGTATCGTATCCCCGTGCCAATGGCAGACCGGTGCATGCAAGGTCTGCCAACTCTGTCGGACGTTGCGATGCGAACCTTGAGTATAGCCTTGCATGCGATGCGAACAAACAGCGTTGCCTTGACCTATCACGGGTATCGTATCCCAACTCTTCGTCATTCGCAAGCGAACGCTTTGCGTCTGCGAAAGACTATGCACGGCGTGCGTCTGCGAATACCAACGATAACCGTGCGAATGTCGAACACATAAGTGAGTATGTCGTGTGTGTCGAACTGCCTGCGCGTTCATAGCCTCCCGGACGCACTGACGGACGCACTGACAGATGCCGAATGAATGAGTACGGTATGTAATTGTTTGCAACCATACGCCTATTCATGTATAAGGCACGTGCCTCTAAGGCTATCATATTGTACACTAGTGCGAACATAGGCATTTGCCTTGAGTAAAGCAATATGTATTGTTGGGTGTATGTCGTTGTGTGATCACTGCCTGCCGGTGCCCTGTCAAGCGATCCATGCCTAATCAACCGTGCGGAACGTGACGGACGGCCTATCAATGACGATATCCATCCCATAGGCCTGGAATCGCTAGACTTAAGTGAGTACGTATCATGCGGACCCTCACTCAGTCCCTCACACGTAGGCAGTATCAGTGCCGGTAAGTGTGTCGCTTCGCATACGAACAAAGACACTAGCCTTATCAATGCAAGGTCTGCGGCATTCAACATATGCATATTGGTTGAGTATCCAAGCCTAATCAACGTAGAGTAATCACTCTTGTAAATGTATCCGCCTAAGCAACCAAGGTCTGCGGCAAGGTACCGTGCATACTATGTCCTAGGCAATGCGTCTGCCGGACGGCTACTGCACAAATCATGCGCTGCCAACAATTACGGTCCACAGTCATAGCACCGTGCATCCCGACGGTACCTTGAGTATTACCTTGCAATGTACCTACTCGGTGCATAGTATAAGGCTTAGTACGGACGTGTGTACAGACTCGTAACAATCAACGAAACGAAATGCCTAAGCGAAAGTGAGTATAGGTGATTGTACCGTGCGCTTAAGCCTAAGAAAGAGCCTGTCGTATGCCTTATCATACAGTAAGCAATGTTAATGAATAAGGCACGGTACAAAGACACTTCGAAAACAGGCGACGTTTGTTGGGTGTATAGTGTCGCATTCTACCTACACAGTTCGTCTTCGTCTATGGAATGCTCTCCAATGTACCGTGCGTGATGTATCATGCGATCATTCGGAAGGTCTGCCGCTGCGAACAAACGCTTTGCAAGGTCAAGCGATAGCCTGTAATGCCTATTGCGTCCAATCAATGCCGCATTCTATGCCCTGTCAAGCGATAGCCTTATCAAATACGCATAGTATCCATACGGAGCGTACAGTGGCCAACCAATGTACGTAGGCACATCACTCAGTGCCGCTAAGGCTGTCGCTGCGAACCTTGCGGTAAGCGAATTCAAAGACTTTGCACCCTCTTGCCACTGATCACCGCGATTGCCTGTGTGTCCCGGTTGGTATCCGCTGGTATTGTAAATGTAACCGTTACTGCCTCCACAGCCACAGCCTTCCATGTCATTCATTAAGCGACCACTGTCTATCCATCCGTCTGCCCGTGCGAACGTATCATCCGGTCCCCTAATCCTAATCCTAATGTACATTAACGATGCGAATAGTTGGTACCTTGAGTAATTCGTACCGTATACACCGTCTACCGCTGACGCTAAGAACGTATCGTAAATGTATGTCGAACTCGATGGCGGAAGTAACACTTGGTCTGAGAACATTTGCGATGCAAGCCGTGCCGTAGACAGTAAGAATAAGGCACGGTCACCCTCACAGGATCCCATGCCACGTTGCCGTGCCGCTAACATGTATTCACGGCACTTAACAACGGTGCTATAGTAACAGTTACACGAAATGCCACTCCATGGCGGAAGTAACATGTGATCACTCTACTCACACAAATAGTAATTCATTAAGGCTCCACTGTCAGGCGGACGGCCTTCCATGGAACGTACCTTGAAAACAACGGTGCTAACACTGTACTTAAGCATAGGTCCCCGATACGACGGAACACTGTATAGGCCAGAGTACAATAACATTTGTTGGGTGGTTGCATAGCCATGGGTGAATAAGCCACGTTGCCTAATCGACACTATGTAACCACCCCTGCCTCCAACCGATGAGTCACGGCCATCGTACATAGGCATTTGCGGTAACCGACTCACTGCGGCTATCAATAGTCCGCCTTACATGTAAATGTAACACAAACCAGTCACTTCCATGGTTCCATAGTACCTTGAGTATCCACCCTCTAACCATAGCCTGGATGACGTTAAGTAAAGTGAGTATCCCATGGTATCGTAAATGTAATAGCCTGGCCGAAGTGAGTACATAGCGCAAAGCGAACTGCCTGCGCAACGCTGTGCACTGTTGCCTGCAGAGCCTGCGAATGGGCCTATGTACTTAAGCGAACTGCAACGCTGTGCACTGTTGCCTGCACTCAGTGCGAATTGGTGAGGCGACTCAGGCCTTGCACCCCACATTGCACTGTTGCCTGCGAAACACGCACACGCTAAGTGTATCTAACGTGCCATGCCTTCACGCCGATACGACGGTCCGCAAGGTGCGTGTATGTGTATCGCAGGCGGTGGGAACAATAACATTTGCTCTGGTAGCATAGAGTATCCCAGACTGGTAAGCACTAGGCGACCCCTGTCTGCAGGCCTACGCTTGAAAATCGCATCATTCACTGCCGCTAACGTGGTTAAGTATTCACGGCACTTTCCAACCCATTGGCTATGCTCTGCCAACTTTATCCGTCCGTCTGCAAGGTCTGCCCACGGTGCACCGTTATACGGACACCGAATGTTGAATAAGCCACTGTTACCGTTAAGCCTAACACGGGTGTCACCGTTACGTGCCGGTGGCTTACTGAATTACTTAAGGTACCTTGAGTAAACGGTAACATCCGCTGCCGGTGGGTCTGACGGTGGCAGAGCCGGTGGCAATGCGAACCTTTACAGTGCGCGAGTGTCTGGTTCGGTGCAATTCGCTGCGAAACACGATGAGTCAGGCGAATGCTTAATGTAATAGCCTGGCCGAAGTGAGTACGCTGCGAAATCGGCAACAGCCCGTGCCGCTGCCTCTAACAATGCCGGTTCGTGTGTCATGTAAGACGTTTGTGCCAATAACAACTGTCCGTCTGCAATGTACATTAAGCGTTGCGCAGCAGCGTACATACCACCGCCTGAGTATCCCTCTAACAATGCGTGATAGTACCTTGAGTATCCATAGCCTGGCCGTGAGTGTGCGTGATAGTATAGGCACCTAAGTCCCGCTAAGTTAATCCGTGCCAATGGCATGTAATTGTTAATGCCATAGCCACGTGCGAATATCATGTAAAGTGAGTATGTGTGTGTGTGTCACGCAATGTGTGCGTCTGCCGCAGAGGCAGCCGCTGCCGTACCCTACTGATTCGTTACGCTACGTAACGATGCGAATGAGTACATAGGTGCCCGATACGACGGTATCATTGCAAGGTCTGCCGGACGCCGTGCCGACCGACGTGCCGTACCCTACTGAGCAACCGGTGCCGTATTCAGTAAGAACATTGAGCCTAACGGTAAGTGTGTGTGTATGTGTATCGCTAACGTTTGTCCCAATAAGTACAATGGCATTGCATACGCACGCTCATGCAACTAAGTCATTAAGGAACGCGTAGGTACCTTGAATATCATTGCAATGTACATTAAGCGTTGCATTTGCGATGCATACCGTAGCGATCCCCTGTCTGCAAGGTCTGCCGGTGCCCGTGCCATGCCTTCACGGAATACCAATAAGCCATCCCGACGGTACGTACCAGCCTGACCCCACCAAATCGTATTCAGTAACCGTGCATAGTATAACAGATGCCATCCGCCTGCCAACATTATCAAATAGCCATGTGCCGCTAACGTGTAATGCCATGCGCCTGCATAGTATCCCTCTGTCATACGGTGATGGCGACGCGGTTCCCATGCGCATTGCACAAGGAACCTTGTCGCAATCATAGGTGCCAACCTAATCGGTCCATGCGATGCCCGTGCGAACATTAAGTCTGTCAATTGTGCGGACATTACAGGGAACAAAGTCCTATGCCGTGCATGCGCACGCGTAAGGTCTGCCATGCCATCGTATCCGTCTGGCATTTGCCTTGAGTAACGTAAGTCTGTGAATGGCGGTAACTCTACGCTACTGTACATAGGCGAACTCGCTAAGTTAATCCGTGCGAAATGCGATGCACGGCGACGGGTGAATAGTTGGTATATCATGCAAGGTCCCTCTGGCCTAAGCGGACGCATATCCCTGTCTGCATAGTACGATTACCAAGCAGAGCGATTCGTACCCTGATCCTACGCTGCAAGGTATCCGCGACGCAGTGCCAATGGCATGTAATACAAATCATCGAATGAGTACCGTGCAAGCAATATGTACATTATCAAAGTGAAAAGCCTACCGCCAATGTAATAGTATAAGGAAGAGCCTTGTTGGGTGTATCCACCCTGTGAGTGTCCCGCTGGCGCACCCCTAATCGACACATTGTAAATGTAACGCGGTATCAATCCAGCCAGACACATAGGCCATAGGCCAGACCGTATCGTGCGTGCACCCAATATGCGACCCTCTTCGCTGAAACCACCGCGTATCCTGTCTGCAGACGGATAGCCTGAGTTAATGCCTCCCGTAGCCGGACCCCGATTCGACGATCCACGGGTATACATAAGCAGTGAGTGATGCGGAATCCGTCCCAGACTCAATAGGCTGGAATTCAGACGCGGACGCGAACGTTGGTCTGCGGATAGGCCTTAGAACGGTGGCGTTTCAAGGTCTGCGAACCGTAACCTTGTCGGTAACCGACTGTGACCAACGTATCCCAATTGCGGTGTGTGACCCCATGCCAGAACGTCTGCCAACATTGCGAATAGTGCCGGTAACCGACTCACTGCGGATGCCTTAGGCAACATTCCAATGCCTGCCTTAACCGTATTCCGACCCTTAAGCCTACCGCGTGCCGGATGCGGATGCCGAACGCGATGCCTGTCTGCAGGCTTGTATCCGGATTGTGTGTACCTTGAGTAATTCATACGCGTAATGTAAGAGCAAGAGCAACCAGAGTTACCGAACGGATGTATGCGAAGGCGACCGTATATGTCATACTTACCGTTGGCATCGAAACCAGAGTTAATCCTGTCTGCGGCATTCAAACGCGTTGTCCTTGGCGGATACGCAATGAAACCAGAGGATGAGCTAAGGCGACCGTGATGCGTGTGATCACTGCCTGCGAACCGTGCGTGATGCGTTGTCGAACTGCCTGCAATGTACGCTGCGAAAATCGGTGAGTCAATGTAATCGGCTGCACCCTGTGCGAACGCACCGTAAAGTGAGTACTTACCGTGTGCGTCTGCACCGTACCTATGTGCGGCAAGGTATCCCCGTGCCCTATGGTATAGGTATCCCGTATCCGACGGAATGTAATTGTTAAGCACTCCACCCGACTTTTCGTGAAGCGTTGCACACCGACGCCACGAATTCGATTGTCCCAGACTCTTACTCTCAAGCATGTAATTCATATTGTATCCATAGCGATTCGGATGCATAATCCGTCCCAACTCAAGCAAACTCAGTTACCGACTCAGTGCACGGGTATCGTACTTAGGTGCCTACAGAAGCCAAGAGTAACGCCGAGGTGCGAATTGCGGTGCCCGTGCCGTACGGTGTGCCAATTGGTATAAGGCATTGCCTCCCAGTGCGCGTATCTACTTATAGTAAGAGCCAGACCGTAGTGCGAATTGGGTGGTTGCATAGCCTGGCCGTTCCATGTCTGCAACGGTAACCGACGCTGCGAAACCAACCATGTAACTGTTTAAGTAACACGCACACGCTACACGCTGTGCCAGTGGGCCTGCGGTGTGAGGCGAATAGTAATCGGCAACAGCGAATAGGGTATTGTATCCCCGTGCGGTACCCGGATCCCTACAGCGACGCAATGGCATGTATTGCCATGCACCGTGTGCCCTGTCTGCACAGCCTGGCCGTCC';
data='AATGTACAATGTGTAAAGCCGATCACACTCTGCCACTAAGTTAATGTGTGTGTGTGTGAGACGCAATGCCGCTAAGTACCTATTCGATGCGTCTGCGAAAATGTATATGTCTGCACCCTCTTGCCACGTTGTCGTTGTCGCTGCGCGTGCAAGGTCTGCCGCTGCCGATTACCACTATCCGGAACGCGCTAACGGATCACCCAGTCCCTTATGGTTATTCAACCGTTAGTATGAGTATCCAAGCCGATCCACATAGTACGAACTCTGTATGTCTGTGTAATCAATGTCAGGGTCTGCGAACAATAAGCGACCAGGCAACGAATTCGCTGCGCGTATGTCTGAGAAAATGTAAAGCCTTGCATCGGCATGCTCACCGGTGTAATTCCTATGCGGATACACATTGCCTAGTAACGACAGAAGCCGATCACACAGACGCTCTAGGCATAGCTTAACGAACAATTGTGCCGGAAGCGTATTGTTAATGTCTGCCGACAGTAAGTAAAGCCGATCACAGAACGCTAAGTTAATCTCACGTGTCGACCGATTCTAACTCGCTGCAGCCTCACACAATCCGGTGGTTTGTGCCACTAACATGCCAGGCGTTGGCGGTCCACCCTCACACACATTCAATAGCCTATTCAATAGCCTACGGTACTCATGCAATAAGCCTTCAGAGCCTCCCCTAATCGACACATGCGATGCGAAACCACCGGATAAGAGTCCCAACTCTGTCGGTTGCCTACGCTTTCCGGATGACAGTAACAAACGTTAGCTGAATACGCTAGGCCAATGCTGACGTGTGTTGTCTTCACCGAACCTAATCGAACACAAAGACTTTGCGTCTGCACGGTGAGGCCTGAATTGTTGGGTGTAAAGCTAAATCAATACAAGGTATGAGTACATATCGTGTGTGAGTCCATGCTTGCCTTAGCGTATGTCTGACTTAACGCTTAACTCAATGCGATGCGGTTCAACGTCTGTGGTAGACTGTCCCAACAAATCACGGCACAGATGTACCATATCGTGTGTGAGTCCCAACAAATCACGGCACAGATGTACCCTAATCGACACTGGCAAATCACAGAACATATCGTGTGTGAGAGGCATTTAGGCTCCAAGCCGATCCACACAGTACAATTGTGCCATGTTATGCTCATGCTAAAGTAAGAACCGTGCGTCTGTCACTTCGCATAGCAGTGCATCGGCATGCTCAAGCGTGTGTGTGAGTCCATTCGCAAGCGACCTACCGCGTGCGTTACCATTCATGAAACCGGTTGCACGGTTATGCTCTATCATGTATCCAACGTACCAAACACTGGTGGCAATGTAACGTTGCGATGCCTCATGCCGATTGAACCGTTGCCGATGTGAGTACAAACCGCGTATGAAATTGGCACGCAATATGCGTATGCGTAAGCCATTCATAAGCAATATGTAAACACTGTACTCATGCTCATTCAATTGTGCCTCACCGCGTGTGAACAATAACGGACGTAAGCCTACCAACGATTACTATAAGAAAAGCCGATCACAGCACAGATGTACCAATAGGTATGTCGTGTGTGTGAAACACAATAGTTGCGTATCCAGAACCAACGAAAGTTACCGTGCGAATAGGTGTGCCGTATTCCGTGTGCGACGCAGTGCCAACAAAAGTAACGTGTCATGTAGCGCTGCCTACCTACACAGTGACGATAGTGCCCGTGCGTTACCCATGGTTCCAAGGTCTGCCAATGGCAGACCGCTGTGTAGCCTAGCAAGCACACTGAACTAACTCAGTGGCCTTGAGGCTACGAAAAGTATCAATGCCCTGTCTGCGGCATTCAAACGCGTTGTGTTAAGTCCGTGATAGTACTAAAGCACACTCTCTGCAACGGATGGGCCTCCGCCTTGCAGTGCCGTGTGAGTCGTTGAGTATGAGGAACCAAGGAACTAACTCTTATCAATGTATTCCATATAGCCTGTGTGTGTGTGTCACATACCCTATAGGAACGATTACGTAGAGTGTGTGTGTGTGAGACCAGTCGGATGCATAGGGTACCAAAGCAAACCGAATATGTAAAGCTCAAGCGGTATCACTATCGCTGAGTATCCAAGGTCTGCCGTGTGAGTCGTTGAGTATGAGGAACCAAGGAATTACGGACCCATATCGTGAGGCAACAAAGAGCGACCATTGCCTGTGTGATCCAGAGGGTACCGTGCACGGGTATCGTATCCCCGTGCCAATGGCAGACCGGTGCATGCAAGGTCTGCCAACTCTGTCGGACGTTGCGATGCGAACCTTGAGTATAGCCTTGCATGCGATGCGAACAAACAGCGTTGCCTTGACCTATCACGGGTATCGTATCCCAACTCTTCGTCATTCGCAAGCGAACGCTTTGCGTCTGCGAAAGACTATGCACGGCGTGCGTCTGCGAATACCAACGATAACCGTGCGAATGTCGAACACATAAGTGAGTATGTCGTGTGTGTCGAACTGCCTGCGCGTTCATAGCCTCCCGGACGCACTGACGGACGCACTGACAGATGCCGAATGAATGAGTACGGTATGTAATTGTTTGCAACCATACGCCTATTCATGTATAAGGCACGTGCCTCTAAGGCTATCATATTGTACACTAGTGCGAACATAGGCATTTGCCTTGAGTAAAGCAATATGTATTGTTGGGTGTATGTCGTTGTGTGATCACTGCCTGCCGGTGCCCTGTCAAGCGATCCATGCCTAATCAACCGTGCGGAACGTGACGGACGGCCTATCAATGACGATATCCATCCCATAGGCCTGGAATCGCTAGACTTAAGTGAGTACGTATCATGCGGACCCTCACTCAGTCCCTCACACGTAGGCAGTATCAGTGCCGGTAAGTGTGTCGCTTCGCATACGAACAAAGACACTAGCCTTATCAATGCAAGGTCTGCGGCATTCAACATATGCATATTGGTTGAGTATCCAAGCCTAATCAACGTAGAGTAATCACTCTTGTAAATGTATCCGCCTAAGCAACCAAGGTCTGCGGCAAGGTACCGTGCATACTATGTCCTAGGCAATGCGTCTGCCGGACGGCTACTGCACAAATCATGCGCTGCCAACAATTACGGTCCACAGTCATAGCACCGTGCATCCCGACGGTACCTTGAGTATTACCTTGCAATGTACCTACTCGGTGCATAGTATAAGGCTTAGTACGGACGTGTGTACAGACTCGTAACAATCAACGAAACGAAATGCCTAAGCGAAAGTGAGTATAGGTGATTGTACCGTGCGCTTAAGCCTAAGAAAGAGCCTGTCGTATGCCTTATCATACAGTAAGCAATGTTAATGAATAAGGCACGGTACAAAGACACTTCGAAAACAGGCGACGTTTGTTGGGTGTATAGTGTCGCATTCTACCTACACAGTTCGTCTTCGTCTATGGAATGCTCTCCAATGTACCGTGCGTGATGTATCATGCGATCATTCGGAAGGTCTGCCGCTGCGAACAAACGCTTTGCAAGGTCAAGCGATAGCCTGTAATGCCTATTGCGTCCAATCAATGCCGCATTCTATGCCCTGTCAAGCGATAGCCTTATCAAATACGCATAGTATCCATACGGAGCGTACAGTGGCCAACCAATGTACGTAGGCACATCACTCAGTGCCGCTAAGGCTGTCGCTGCGAACCTTGCGGTAAGCGAATTCAAAGACTTTGCACCCTCTTGCCACTGATCACCGCGATTGCCTGTGTGTCCCGGTTGGTATCCGCTGGTATTGTAAATGTAACCGTTACTGCCTCCACAGCCACAGCCTTCCATGTCATTCATTAAGCGACCACTGTCTATCCATCCGTCTGCCCGTGCGAACGTATCATCCGGTCCCCTAATCCTAATCCTAATGTACATTAACGATGCGAATAGTTGGTACCTTGAGTAATTCGTACCGTATACACCGTCTACCGCTGACGCTAAGAACGTATCGTAAATGTATGTCGAACTCGATGGCGGAAGTAACACTTGGTCTGAGAACATTTGCGATGCAAGCCGTGCCGTAGACAGTAAGAATAAGGCACGGTCACCCTCACAGGATCCCATGCCACGTTGCCGTGCCGCTAACATGTATTCACGGCACTTAACAACGGTGCTATAGTAACAGTTACACGAAATGCCACTCCATGGCGGAAGTAACATGTGATCACTCTACTCACACAAATAGTAATTCATTAAGGCTCCACTGTCAGGCGGACGGCCTTCCATGGAACGTACCTTGAAAACAACGGTGCTAACACTGTACTTAAGCATAGGTCCCCGATACGACGGAACACTGTATAGGCCAGAGTACAATAACATTTGTTGGGTGGTTGCATAGCCATGGGTGAATAAGCCACGTTGCCTAATCGACACTATGTAACCACCCCTGCCTCCAACCGATGAGTCACGGCCATCGTACATAGGCATTTGCGGTAACCGACTCACTGCGGCTATCAATAGTCCGCCTTACATGTAAATGTAACACAAACCAGTCACTTCCATGGTTCCATAGTACCTTGAGTATCCACCCTCTAACCATAGCCTGGATGACGTTAAGTAAAGTGAGTATCCCATGGTATCGTAAATGTAATAGCCTGGCCGAAGTGAGTACATAGCGCAAAGCGAACTGCCTGCGCAACGCTGTGCACTGTTGCCTGCAGAGCCTGCGAATGGGCCTATGTACTTAAGCGAACTGCAACGCTGTGCACTGTTGCCTGCACTCAGTGCGAATTGGTGAGGCGACTCAGGCCTTGCACCCCACATTGCACTGTTGCCTGCGAAACACGCACACGCTAAGTGTATCTAACGTGCCATGCCTTCACGCCGATACGACGGTCCGCAAGGTGCGTGTATGTGTATCGCAGGCGGTGGGAACAATAACATTTGCTCTGGTAGCATAGAGTATCCCAGACTGGTAAGCACTAGGCGACCCCTGTCTGCAGGCCTACGCTTGAAAATCGCATCATTCACTGCCGCTAACGTGGTTAAGTATTCACGGCACTTTCCAACCCATTGGCTATGCTCTGCCAACTTTATCCGTCCGTCTGCAAGGTCTGCCCACGGTGCACCGTTATACGGACACCGAATGTTGAATAAGCCACTGTTACCGTTAAGCCTAACACGGGTGTCACCGTTACGTGCCGGTGGCTTACTGAATTACTTAAGGTACCTTGAGTAAACGGTAACATCCGCTGCCGGTGGGTCTGACGGTGGCAGAGCCGGTGGCAATGCGAACCTTTACAGTGCGCGAGTGTCTGGTTCGGTGCAATTCGCTGCGAAACACGATGAGTCAGGCGAATGCTTAATGTAATAGCCTGGCCGAAGTGAGTACGCTGCGAAATCGGCAACAGCCCGTGCCGCTGCCTCTAACAATGCCGGTTCGTGTGTCATGTAAGACGTTTGTGCCAATAACAACTGTCCGTCTGCAATGTACATTAAGCGTTGCGCAGCAGCGTACATACCACCGCCTGAGTATCCCTCTAACAATGCGTGATAGTACCTTGAGTATCCATAGCCTGGCCGTGAGTGTGCGTGATAGTATAGGCACCTAAGTCCCGCTAAGTTAATCCGTGCCAATGGCATGTAATTGTTAATGCCATAGCCACGTGCGAATATCATGTAAAGTGAGTATGTGTGTGTGTGTCACGCAATGTGTGCGTCTGCCGCAGAGGCAGCCGCTGCCGTACCCTACTGATTCGTTACGCTACGTAACGATGCGAATGAGTACATAGGTGCCCGATACGACGGTATCATTGCAAGGTCTGCCGGACGCCGTGCCGACCGACGTGCCGTACCCTACTGAGCAACCGGTGCCGTATTCAGTAAGAACATTGAGCCTAACGGTAAGTGTGTGTGTATGTGTATCGCTAACGTTTGTCCCAATAAGTACAATGGCATTGCATACGCACGCTCATGCAACTAAGTCATTAAGGAACGCGTAGGTACCTTGAATATCATTGCAATGTACATTAAGCGTTGCATTTGCGATGCATACCGTAGCGATCCCCTGTCTGCAAGGTCTGCCGGTGCCCGTGCCATGCCTTCACGGAATACCAATAAGCCATCCCGACGGTACGTACCAGCCTGACCCCACCAAATCGTATTCAGTAACCGTGCATAGTATAACAGATGCCATCCGCCTGCCAACATTATCAAATAGCCATGTGCCGCTAACGTGTAATGCCATGCGCCTGCATAGTATCCCTCTGTCATACGGTGATGGCGACGCGGTTCCCATGCGCATTGCACAAGGAACCTTGTCGCAATCATAGGTGCCAACCTAATCGGTCCATGCGATGCCCGTGCGAACATTAAGTCTGTCAATTGTGCGGACATTACAGGGAACAAAGTCCTATGCCGTGCATGCGCACGCGTAAGGTCTGCCATGCCATCGTATCCGTCTGGCATTTGCCTTGAGTAACGTAAGTCTGTGAATGGCGGTAACTCTACGCTACTGTACATAGGCGAACTCGCTAAGTTAATCCGTGCGAAATGCGATGCACGGCGACGGGTGAATAGTTGGTATATCATGCAAGGTCCCTCTGGCCTAAGCGGACGCATATCCCTGTCTGCATAGTACGATTACCAAGCAGAGCGATTCGTACCCTGATCCTACGCTGCAAGGTATCCGCGACGCAGTGCCAATGGCATGTAATACAAATCATCGAATGAGTACCGTGCAAGCAATATGTACATTATCAAAGTGAAAAGCCTACCGCCAATGTAATAGTATAAGGAAGAGCCTTGTTGGGTGTATCCACCCTGTGAGTGTCCCGCTGGCGCACCCCTAATCGACACATTGTAAATGTAACGCGGTATCAATCCAGCCAGACACATAGGCCATAGGCCAGACCGTATCGTGCGTGCACCCAATATGCGACCCTCTTCGCTGAAACCACCGCGTATCCTGTCTGCAGACGGATAGCCTGAGTTAATGCCTCCCGTAGCCGGACCCCGATTCGACGATCCACGGGTATACATAAGCAGTGAGTGATGCGGAATCCGTCCCAGACTCAATAGGCTGGAATTCAGACGCGGACGCGAACGTTGGTCTGCGGATAGGCCTTAGAACGGTGGCGTTTCAAGGTCTGCGAACCGTAACCTTGTCGGTAACCGACTGTGACCAACGTATCCCAATTGCGGTGTGTGACCCCATGCCAGAACGTCTGCCAACATTGCGAATAGTGCCGGTAACCGACTCACTGCGGATGCCTTAGGCAACATTCCAATGCCTGCCTTAACCGTATTCCGACCCTTAAGCCTACCGCGTGCCGGATGCGGATGCCGAACGCGATGCCTGTCTGCAGGCTTGTATCCGGATTGTGTGTACCTTGAGTAATTCATACGCGTAATGTAAGAGCAAGAGCAACCAGAGTTACCGAACGGATGTATGCGAAGGCGACCGTATATGTCATACTTACCGTTGGCATCGAAACCAGAGTTAATCCTGTCTGCGGCATTCAAACGCGTTGTCCTTGGCGGATACGCAATGAAACCAGAGGATGAGCTAAGGCGACCGTGATGCGTGTGATCACTGCCTGCGAACCGTGCGTGATGCGTTGTCGAACTGCCTGCAATGTACGCTGCGAAAATCGGTGAGTCAATGTAATCGGCTGCACCCTGTGCGAACGCACCGTAAAGTGAGTACTTACCGTGTGCGTCTGCACCGTACCTATGTGCGGCAAGGTATCCCCGTGCCCTATGGTATAGGTATCCCGTATCCGACGGAATGTAATTGTTAAGCACTCCACCCGACTTTTCGTGAAGCGTTGCACACCGACGCCACGAATTCGATTGTCCCAGACTCTTACTCTCAAGCATGTAATTCATATTGTATCCATAGCGATTCGGATGCATAATCCGTCCCAACTCAAGCAAACTCAGTTACCGACTCAGTGCACGGGTATCGTACTTAGGTGCCTACAGAAGCCAAGAGTAACGCCGAGGTGCGAATTGCGGTGCCCGTGCCGTACGGTGTGCCAATTGGTATAAGGCATTGCCTCCCAGTGCGCGTATCTACTTATAGTAAGAGCCAGACCGTAGTGCGAATTGGGTGGTTGCATAGCCTGGCCGTTCCATGTCTGCAACGGTAACCGACGCTGCGAAACCAACCATGTAACTGTTTAAGTAACACGCACACGCTACACGCTGTGCCAGTGGGCCTGCGGTGTGAGGCGAATAGTAATCGGCAACAGCGAATAGGGTATTGTATCCCCGTGCGGTACCCGGATCCCTACAGCGACGCAATGGCATGTATTGCCATGCACCGTGTGCCCTGTCTGCACAGCCTGGCCGTCCGAA';
% data='AATGTACAATGTGTAAAGCCGATCACACTCTGCCACTAAGTTAATGTG';
data_length = length(data);
%块1
seq_1='';
num_seq_1='';
%块2
seq_2='';
num_seq_2='';
%块3
seq_3='';
num_seq_3='';
%块4
seq_4='';
num_seq_4='';
%块5
seq_5='';
num_seq_5='';
%块6
seq_6='';
num_seq_6='';
%块7
seq_7='';
num_seq_7='';

%缓冲段
buff_seq_1 = '';
buff_seq_2 = '';
buff_seq_3 = '';

%新序列
re_DNA_chr = '';

i=1;
while i<=data_length
    %第一段
    for j1=1:4
        seq_1 = strcat(seq_1,data(i));
        if data(i) == 'A'
            num_seq_1 = strcat(num_seq_1,'00');
        elseif data(i) == 'T'
            num_seq_1 = strcat(num_seq_1,'01');
        elseif data(i) == 'C'
            num_seq_1 = strcat(num_seq_1,'10');
        elseif data(i) == 'G'
            num_seq_1 = strcat(num_seq_1,'11');
        end
        i=i+1;
    end
    %第二段
    for j2=1:4
        seq_2 = strcat(seq_2,data(i));
        if data(i) == 'A'
            num_seq_2 = strcat(num_seq_2,'00');
        elseif data(i) == 'T'
            num_seq_2 = strcat(num_seq_2,'01');
        elseif data(i) == 'C'
            num_seq_2 = strcat(num_seq_2,'10');
        elseif data(i) == 'G'
            num_seq_2 = strcat(num_seq_2,'11');
        end
        i=i+1;
    end
    %第三段
    for j3=1:4
        seq_3 = strcat(seq_3,data(i));
        if data(i) == 'A'
            num_seq_3 = strcat(num_seq_3,'00');
        elseif data(i) == 'T'
            num_seq_3 = strcat(num_seq_3,'01');
        elseif data(i) == 'C'
            num_seq_3 = strcat(num_seq_3,'10');
        elseif data(i) == 'G'
            num_seq_3 = strcat(num_seq_3,'11');
        end
        i=i+1;
    end
    %第四段
    for j4=1:3
        seq_4 = strcat(seq_4,data(i));
        if data(i) == 'A'
            num_seq_4 = strcat(num_seq_4,'00');
        elseif data(i) == 'T'
            num_seq_4 = strcat(num_seq_4,'01');
        elseif data(i) == 'C'
            num_seq_4 = strcat(num_seq_4,'10');
        elseif data(i) == 'G'
            num_seq_4 = strcat(num_seq_4,'11');
        end
        i=i+1;
    end
    %第五段
    for j5=1:3
        seq_5 = strcat(seq_5,data(i));
        if data(i) == 'A'
            num_seq_5 = strcat(num_seq_5,'00');
        elseif data(i) == 'T'
            num_seq_5 = strcat(num_seq_5,'01');
        elseif data(i) == 'C'
            num_seq_5 = strcat(num_seq_5,'10');
        elseif data(i) == 'G'
            num_seq_5 = strcat(num_seq_5,'11');
        end
        i=i+1;
    end
    %第六段
    for j6=1:3
        seq_6 = strcat(seq_6,data(i));
        if data(i) == 'A'
            num_seq_6 = strcat(num_seq_6,'00');
        elseif data(i) == 'T'
            num_seq_6 = strcat(num_seq_6,'01');
        elseif data(i) == 'C'
            num_seq_6 = strcat(num_seq_6,'10');
        elseif data(i) == 'G'
            num_seq_6 = strcat(num_seq_6,'11');
        end
        i=i+1;
    end
    %第七段
    for j7=1:3
        seq_7 = strcat(seq_7,data(i));
        if data(i) == 'A'
            num_seq_7 = strcat(num_seq_7,'00');
        elseif data(i) == 'T'
            num_seq_7 = strcat(num_seq_7,'01');
        elseif data(i) == 'C'
            num_seq_7 = strcat(num_seq_7,'10');
        elseif data(i) == 'G'
            num_seq_7 = strcat(num_seq_7,'11');
        end
        i=i+1;
    end
    %把第7段拆分给456
    num_seq_4 = strcat(strcat(num_seq_4,num_seq_7(1)),num_seq_7(2));
    num_seq_5 = strcat(strcat(num_seq_5,num_seq_7(3)),num_seq_7(4));
    num_seq_6 = strcat(strcat(num_seq_6,num_seq_7(5)),num_seq_7(6));
    %重构
    for re_i = 1:8
        buff_seq_1 = strcat(strcat(buff_seq_1,num_seq_1(re_i)),num_seq_4(re_i));
        buff_seq_2 = strcat(strcat(buff_seq_2,num_seq_2(re_i)),num_seq_5(re_i));
        buff_seq_3 = strcat(strcat(buff_seq_3,num_seq_3(re_i)),num_seq_6(re_i));
    end
    %转换成碱基
    re_DNA_1 = 1;
    re_DNA_2 = 1;
    re_DNA_3 = 1;
    while re_DNA_1 <= 16
        buff_re_DNA = '';
        buff_re_DNA = strcat(buff_re_DNA,buff_seq_1(re_DNA_1));
        re_DNA_1 = re_DNA_1 +1;
        buff_re_DNA = strcat(buff_re_DNA,buff_seq_1(re_DNA_1));
        re_DNA_1 = re_DNA_1 +1;
        if buff_re_DNA == '00'
            re_DNA_chr = strcat(re_DNA_chr,'A');
        elseif buff_re_DNA == '01'
            re_DNA_chr = strcat(re_DNA_chr,'C');
        elseif buff_re_DNA == '10'
            re_DNA_chr = strcat(re_DNA_chr,'T');
        elseif buff_re_DNA == '11'
            re_DNA_chr = strcat(re_DNA_chr,'G');
        end
    end
    while re_DNA_2 <= 16
        buff_re_DNA = '';
        buff_re_DNA = strcat(buff_re_DNA,buff_seq_2(re_DNA_2));
        re_DNA_2 = re_DNA_2 +1;
        buff_re_DNA = strcat(buff_re_DNA,buff_seq_2(re_DNA_2));
        re_DNA_2 = re_DNA_2 +1;
        if buff_re_DNA == '00'
            re_DNA_chr = strcat(re_DNA_chr,'A');
        elseif buff_re_DNA == '01'
            re_DNA_chr = strcat(re_DNA_chr,'C');
        elseif buff_re_DNA == '10'
            re_DNA_chr = strcat(re_DNA_chr,'T');
        elseif buff_re_DNA == '11'
            re_DNA_chr = strcat(re_DNA_chr,'G');
        end
    end
    while re_DNA_3 <= 16
        buff_re_DNA = '';
        buff_re_DNA = strcat(buff_re_DNA,buff_seq_3(re_DNA_3));
        re_DNA_3 = re_DNA_3 +1;
        buff_re_DNA = strcat(buff_re_DNA,buff_seq_3(re_DNA_3));
        re_DNA_3 = re_DNA_3 +1;
        if buff_re_DNA == '00'
            re_DNA_chr = strcat(re_DNA_chr,'A');
        elseif buff_re_DNA == '01'
            re_DNA_chr = strcat(re_DNA_chr,'C');
        elseif buff_re_DNA == '10'
            re_DNA_chr = strcat(re_DNA_chr,'T');
        elseif buff_re_DNA == '11'
            re_DNA_chr = strcat(re_DNA_chr,'G');
        end
    end
%块1
seq_1='';
num_seq_1='';
%块2
seq_2='';
num_seq_2='';
%块3
seq_3='';
num_seq_3='';
%块4
seq_4='';
num_seq_4='';
%块5
seq_5='';
num_seq_5='';
%块6
seq_6='';
num_seq_6='';
%块7
seq_7='';
num_seq_7='';

%缓冲段
buff_seq_1 = '';
buff_seq_2 = '';
buff_seq_3 = '';
end

%解码
de_re_DNA_chr = '';
re_DNA_chr_L = length(re_DNA_chr);
%块1
de_seq_1='';
de_num_seq_1='';
%块2
de_seq_2='';
de_num_seq_2='';
%块3
de_seq_3='';
de_num_seq_3='';
%块4
de_seq_4='';
de_num_seq_4='';
%块5
de_seq_5='';
de_num_seq_5='';
%块6
de_seq_6='';
de_num_seq_6='';
%块7
de_seq_7='';
de_num_seq_7='';
de_i = 1;
while de_i<=re_DNA_chr_L
    %复原6个8bit的字符串
    for de_1=1:8
        if re_DNA_chr(de_i) == 'A'
            de_num_seq_1 = strcat(de_num_seq_1,'0');
            de_num_seq_4 = strcat(de_num_seq_4,'0');
        elseif re_DNA_chr(de_i) == 'T'
            de_num_seq_1 = strcat(de_num_seq_1,'1');
            de_num_seq_4 = strcat(de_num_seq_4,'0');
        elseif re_DNA_chr(de_i) == 'C'
            de_num_seq_1 = strcat(de_num_seq_1,'0');
            de_num_seq_4 = strcat(de_num_seq_4,'1');
        elseif re_DNA_chr(de_i) == 'G'
            de_num_seq_1 = strcat(de_num_seq_1,'1');
            de_num_seq_4 = strcat(de_num_seq_4,'1');
        end
        de_i = de_i+1;
    end
    for de_2=1:8
        if re_DNA_chr(de_i) == 'A'
            de_num_seq_2 = strcat(de_num_seq_2,'0');
            de_num_seq_5 = strcat(de_num_seq_5,'0');
        elseif re_DNA_chr(de_i) == 'T'
            de_num_seq_2 = strcat(de_num_seq_2,'1');
            de_num_seq_5 = strcat(de_num_seq_5,'0');
        elseif re_DNA_chr(de_i) == 'C'
            de_num_seq_2 = strcat(de_num_seq_2,'0');
            de_num_seq_5 = strcat(de_num_seq_5,'1');
        elseif re_DNA_chr(de_i) == 'G'
            de_num_seq_2 = strcat(de_num_seq_2,'1');
            de_num_seq_5 = strcat(de_num_seq_5,'1');
        end
        de_i = de_i+1;
    end
    for de_3=1:8
        if re_DNA_chr(de_i) == 'A'
            de_num_seq_3 = strcat(de_num_seq_3,'0');
            de_num_seq_6 = strcat(de_num_seq_6,'0');
        elseif re_DNA_chr(de_i) == 'T'
            de_num_seq_3 = strcat(de_num_seq_3,'1');
            de_num_seq_6 = strcat(de_num_seq_6,'0');
        elseif re_DNA_chr(de_i) == 'C'
            de_num_seq_3 = strcat(de_num_seq_3,'0');
            de_num_seq_6 = strcat(de_num_seq_6,'1');
        elseif re_DNA_chr(de_i) == 'G'
            de_num_seq_3 = strcat(de_num_seq_3,'1');
            de_num_seq_6 = strcat(de_num_seq_6,'1');
        end
        de_i = de_i+1;
    end
    %复原块4567
    de_num_seq_7 = strcat(strcat(strcat(de_num_seq_7,de_num_seq_4(7:8)),de_num_seq_5(7:8)),de_num_seq_6(7:8));
    de_num_seq_4 = de_num_seq_4(1:6);
    de_num_seq_5 = de_num_seq_5(1:6);
    de_num_seq_6 = de_num_seq_6(1:6);
    for seq_1_1=1:2:8
        if de_num_seq_1(seq_1_1) == '0'  &&  de_num_seq_1(seq_1_1+1) == '0'
            de_seq_1 = strcat(de_seq_1,'A');
        elseif de_num_seq_1(seq_1_1) == '0'  &&  de_num_seq_1(seq_1_1+1) == '1'
            de_seq_1 = strcat(de_seq_1,'T');
        elseif de_num_seq_1(seq_1_1) == '1'  &&  de_num_seq_1(seq_1_1+1) == '0'
            de_seq_1 = strcat(de_seq_1,'C');
        elseif de_num_seq_1(seq_1_1) == '1'  &&  de_num_seq_1(seq_1_1+1) == '1'
            de_seq_1 = strcat(de_seq_1,'G');
        end
    end
    for seq_2_2=1:2:8
        if de_num_seq_2(seq_2_2) == '0'  &&  de_num_seq_2(seq_2_2+1) == '0'
            de_seq_2 = strcat(de_seq_2,'A');
        elseif de_num_seq_2(seq_2_2) == '0'  &&  de_num_seq_2(seq_2_2+1) == '1'
            de_seq_2 = strcat(de_seq_2,'T');
        elseif de_num_seq_2(seq_2_2) == '1'  &&  de_num_seq_2(seq_2_2+1) == '0'
            de_seq_2 = strcat(de_seq_2,'C');
        elseif de_num_seq_2(seq_2_2) == '1'  &&  de_num_seq_2(seq_2_2+1) == '1'
            de_seq_2 = strcat(de_seq_2,'G');
        end
    end
    for seq_3_3=1:2:8
        if de_num_seq_3(seq_3_3) == '0'  &&  de_num_seq_3(seq_3_3+1) == '0'
            de_seq_3 = strcat(de_seq_3,'A');
        elseif de_num_seq_3(seq_3_3) == '0'  &&  de_num_seq_3(seq_3_3+1) == '1'
            de_seq_3 = strcat(de_seq_3,'T');
        elseif de_num_seq_3(seq_3_3) == '1'  &&  de_num_seq_3(seq_3_3+1) == '0'
            de_seq_3 = strcat(de_seq_3,'C');
        elseif de_num_seq_3(seq_3_3) == '1'  &&  de_num_seq_3(seq_3_3+1) == '1'
            de_seq_3 = strcat(de_seq_3,'G');
        end
    end
    for seq_4_4=1:2:6
        if de_num_seq_4(seq_4_4) == '0'  &&  de_num_seq_4(seq_4_4+1) == '0'
            de_seq_4 = strcat(de_seq_4,'A');
        elseif de_num_seq_4(seq_4_4) == '0'  &&  de_num_seq_4(seq_4_4+1) == '1'
            de_seq_4 = strcat(de_seq_4,'T');
        elseif de_num_seq_4(seq_4_4) == '1'  &&  de_num_seq_4(seq_4_4+1) == '0'
            de_seq_4 = strcat(de_seq_4,'C');
        elseif de_num_seq_4(seq_4_4) == '1'  &&  de_num_seq_4(seq_4_4+1) == '1'
            de_seq_4 = strcat(de_seq_4,'G');
        end
    end
    for seq_5_5=1:2:6
        if de_num_seq_5(seq_5_5) == '0'  &&  de_num_seq_5(seq_5_5+1) == '0'
            de_seq_5 = strcat(de_seq_5,'A');
        elseif de_num_seq_5(seq_5_5) == '0'  &&  de_num_seq_5(seq_5_5+1) == '1'
            de_seq_5 = strcat(de_seq_5,'T');
        elseif de_num_seq_5(seq_5_5) == '1'  &&  de_num_seq_5(seq_5_5+1) == '0'
            de_seq_5 = strcat(de_seq_5,'C');
        elseif de_num_seq_5(seq_5_5) == '1'  &&  de_num_seq_5(seq_5_5+1) == '1'
            de_seq_5 = strcat(de_seq_5,'G');
        end
    end
    for seq_6_6=1:2:6
        if de_num_seq_6(seq_6_6) == '0'  &&  de_num_seq_6(seq_6_6+1) == '0'
            de_seq_6 = strcat(de_seq_6,'A');
        elseif de_num_seq_6(seq_6_6) == '0'  &&  de_num_seq_6(seq_6_6+1) == '1'
            de_seq_6 = strcat(de_seq_6,'T');
        elseif de_num_seq_6(seq_6_6) == '1'  &&  de_num_seq_6(seq_6_6+1) == '0'
            de_seq_6 = strcat(de_seq_6,'C');
        elseif de_num_seq_6(seq_6_6) == '1'  &&  de_num_seq_6(seq_6_6+1) == '1'
            de_seq_6 = strcat(de_seq_6,'G');
        end
    end
    for seq_7_7=1:2:6
        if de_num_seq_7(seq_7_7) == '0'  &&  de_num_seq_7(seq_7_7+1) == '0'
            de_seq_7 = strcat(de_seq_7,'A');
        elseif de_num_seq_7(seq_7_7) == '0'  &&  de_num_seq_7(seq_7_7+1) == '1'
            de_seq_7 = strcat(de_seq_7,'T');
        elseif de_num_seq_7(seq_7_7) == '1'  &&  de_num_seq_7(seq_7_7+1) == '0'
            de_seq_7 = strcat(de_seq_7,'C');
        elseif de_num_seq_7(seq_7_7) == '1'  &&  de_num_seq_7(seq_7_7+1) == '1'
            de_seq_7 = strcat(de_seq_7,'G');
        end
    end
    de_re_DNA_chr = strcat(strcat(strcat(strcat(strcat(strcat(strcat(de_re_DNA_chr,de_seq_1),de_seq_2),de_seq_3),de_seq_4),de_seq_5),de_seq_6),de_seq_7);
   %块1
de_seq_1='';
de_num_seq_1='';
%块2
de_seq_2='';
de_num_seq_2='';
%块3
de_seq_3='';
de_num_seq_3='';
%块4
de_seq_4='';
de_num_seq_4='';
%块5
de_seq_5='';
de_num_seq_5='';
%块6
de_seq_6='';
de_num_seq_6='';
%块7
de_seq_7='';
de_num_seq_7=''; 
end

strcmp(data,de_re_DNA_chr)


